"use client";
import { Suspense,useEffect,useState } from "react";
import { useSearchParams } from "next/navigation";
import { createClient } from "@/utils/supabase/client";
type Details={invitee_name:string|null;professional_name:string;expires_at:string;status:string};
function PatientRegistration(){
 const params=useSearchParams(),token=params.get('token');
 const [invite,setInvite]=useState<Details|null>(null),[loading,setLoading]=useState(true),[invalid,setInvalid]=useState(''),[sent,setSent]=useState(false),[submitting,setSubmitting]=useState(false),[error,setError]=useState('');
 const [form,setForm]=useState({name:'',email:'',phone:'',birthDate:'',password:''});
 useEffect(()=>{(async()=>{if(!token){setInvalid('Este enlace no contiene una invitación. Solicita uno nuevo a tu psicólogo.');setLoading(false);return}const {data,error}=await createClient().rpc('invitation_public_details',{invitation_token:token});const d=data?.[0] as Details|undefined;if(error||!d){setInvalid('No encontramos esta invitación. Revisa que hayas copiado el enlace completo.');setLoading(false);return}if(d.status!=='pending'){setInvalid(d.status==='accepted'?'Esta invitación ya fue utilizada.':'Esta invitación ya no está disponible.');setLoading(false);return}if(new Date(d.expires_at)<new Date()){setInvalid('Esta invitación venció. Solicita un enlace nuevo.');setLoading(false);return}setInvite(d);setForm(x=>({...x,name:d.invitee_name||''}));setLoading(false)})()},[token]);
 const register=async()=>{setError('');if(form.name.trim().length<2||!/^\S+@\S+\.\S+$/.test(form.email)||form.phone.trim().length<8||!form.birthDate||form.password.length<8){setError('Completa todos los datos. La contraseña debe tener al menos 8 caracteres.');return}if(!token)return;setSubmitting(true);const {error}=await createClient().auth.signUp({email:form.email.trim().toLowerCase(),password:form.password,options:{emailRedirectTo:`${window.location.origin}/auth/callback`,data:{full_name:form.name.trim(),phone:form.phone.trim(),birth_date:form.birthDate,invitation_token:token,requested_role:'paciente'}}});setSubmitting(false);if(error){setError(error.message);return}setSent(true)};
 if(loading)return <main className="invite-shell single"><section className="invite-registration-card"><p>Validando invitación…</p></section></main>;
 if(invalid)return <main className="invite-shell single"><section className="invite-registration-card invite-invalid"><div className="invite-symbol">!</div><p className="eyebrow">ENLACE NO DISPONIBLE</p><h1>No pudimos abrir la invitación</h1><p>{invalid}</p><a className="primary" href="/">Volver a Vicino</a></section></main>;
 if(sent)return <main className="invite-shell single"><section className="invite-registration-card invite-confirm"><div className="invite-symbol">✉</div><p className="eyebrow">REVISA TU CORREO</p><h1>Tu espacio está casi listo</h1><p>Enviamos un enlace de confirmación a <strong>{form.email}</strong>. Ábrelo para activar tu cuenta de paciente.</p><div className="mail-tips"><span>El enlace puede tardar unos minutos.</span><span>Si no aparece, revisa la carpeta de spam.</span></div><button className="secondary" onClick={()=>setSent(false)}>Cambiar correo</button></section></main>;
 return <main className="invite-shell"><section className="invite-welcome"><a className="invite-brand" href="/"><img src="/vicino-mark.png" alt=""/><span><strong>vicino</strong><small>CONNECT</small></span></a><div><p className="eyebrow">INVITACIÓN PRIVADA</p><h1>{invite?.professional_name} te invita a Vicino</h1><p>Crea tu espacio personal para acompañar tu proceso de forma segura.</p></div><small>Esta invitación solo permite crear una cuenta de Paciente.</small></section><section className="invite-registration-card"><p className="eyebrow">CREAR MI CUENTA</p><h2>Cuéntanos sobre ti</h2><p className="muted">Estos datos pertenecerán únicamente a tu perfil.</p><label>Nombre completo<input value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></label><label>Correo electrónico<input type="email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/></label><div className="invite-fields"><label>Teléfono<input type="tel" value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})}/></label><label>Fecha de nacimiento<input type="date" value={form.birthDate} onChange={e=>setForm({...form,birthDate:e.target.value})}/></label></div><label>Contraseña<input type="password" value={form.password} onChange={e=>setForm({...form,password:e.target.value})} placeholder="Mínimo 8 caracteres"/></label><label className="privacy-consent"><input type="checkbox" required/> Acepto el Aviso de privacidad y el tratamiento de mis datos.</label>{error&&<p className="auth-message" role="alert">{error}</p>}<button className="primary" disabled={submitting} onClick={register}>{submitting?'Creando cuenta…':'Crear mi espacio'} <span>→</span></button></section></main>;
}

export default function PatientRegistrationPage(){
 return <Suspense fallback={<main className="invite-shell single"><section className="invite-registration-card"><p>Preparando invitación…</p></section></main>}><PatientRegistration/></Suspense>;
}
