"use client";

import { useEffect, useState } from "react";
import { createClient } from "@/utils/supabase/client";

export type PatientCareItem = { id:string; kind:string; resource_type:string; title:string; instructions:string|null; content:{questions?:string[];url?:string;prompt?:string;file_path?:string;file_name?:string;file_type?:string}; frequency:string; created_at:string };

export default function PatientResourceModal({item,onClose}:{item:PatientCareItem;onClose:()=>void}){
 const questions=item.content?.questions||[];
 const [answers,setAnswers]=useState<string[]>(questions.map(()=>'')),[reflection,setReflection]=useState(''),[message,setMessage]=useState(''),[saving,setSaving]=useState(false);
 useEffect(()=>{(async()=>{const client=createClient();const {data:{user}}=await client.auth.getUser();if(!user)return;const today=new Date().toISOString().slice(0,10);const {data}=await client.from('care_item_responses').select('response,status').eq('care_item_id',item.id).eq('patient_id',user.id).eq('response_date',today).maybeSingle();if(data?.response?.answers)setAnswers(data.response.answers);if(data?.response?.reflection)setReflection(data.response.reflection);if(data?.status==='submitted')setMessage('Tu respuesta de hoy ya está guardada. Puedes actualizarla si lo necesitas.')})()},[item.id]);
 const save=async()=>{setSaving(true);setMessage('Guardando…');const client=createClient();const {data:{user}}=await client.auth.getUser();if(!user){setSaving(false);setMessage('Tu sesión venció. Vuelve a iniciar sesión.');return}const response=questions.length?{answers}:{reflection};const {error}=await client.from('care_item_responses').upsert({care_item_id:item.id,patient_id:user.id,response_date:new Date().toISOString().slice(0,10),response,status:'submitted',submitted_at:new Date().toISOString(),updated_at:new Date().toISOString()},{onConflict:'care_item_id,patient_id,response_date'});setSaving(false);setMessage(error?(error.message.includes('care_item_responses')?'Falta activar las respuestas interactivas en Supabase.':error.message):'Respuesta guardada. Tu profesional podrá revisarla de forma segura.')};
 const openFile=async()=>{if(item.content.url){window.open(item.content.url,'_blank','noopener,noreferrer');return}if(!item.content.file_path)return;setMessage('Preparando archivo…');const {data,error}=await createClient().storage.from('care-resources').createSignedUrl(item.content.file_path,120);if(error||!data?.signedUrl){setMessage('No pudimos abrir el archivo. Verifica que el módulo de archivos esté activado.');return}window.open(data.signedUrl,'_blank','noopener,noreferrer');setMessage('')};
 const canRespond=item.resource_type!=='educational_material'||questions.length>0;
 return <div className="modal-backdrop patient-resource-backdrop" onClick={onClose}><section className="modal patient-resource-modal" role="dialog" aria-modal="true" aria-label={item.title} onClick={event=>event.stopPropagation()}><button className="modal-close" aria-label="Cerrar recurso" onClick={onClose}>×</button><p className="eyebrow">RECURSO COMPARTIDO</p><h2>{item.title}</h2><p className="resource-guidance">{item.instructions||item.content?.prompt||'Este recurso forma parte de tu acompañamiento.'}</p>{(item.content.file_path||item.content.url)&&<button className="resource-file-button" onClick={openFile}><span>↓</span><div><strong>{item.content.file_name||'Abrir material'}</strong><small>{item.content.file_path?'Archivo compartido de forma privada':'Enlace compartido'}</small></div></button>}{questions.map((question,index)=><label className="edit-field resource-question" key={`${question}-${index}`}><span>{index+1}. {question}</span><textarea value={answers[index]||''} onChange={event=>setAnswers(current=>current.map((answer,answerIndex)=>answerIndex===index?event.target.value:answer))} placeholder="Escribe aquí con calma…"/></label>)}{!questions.length&&item.resource_type!=='educational_material'&&<label className="edit-field resource-question"><span>Tu respuesta</span><textarea value={reflection} onChange={event=>setReflection(event.target.value)} placeholder="Escribe aquí con calma…"/></label>}{message&&<p className="invite-feedback" role="status">{message}</p>}{canRespond&&<button className="primary" disabled={saving} onClick={save}>{saving?'Guardando…':'Guardar respuesta'}</button>}</section></div>
}
