"use client";
import {useEffect,useState} from "react";
import {createClient} from "@/utils/supabase/client";
export type CareQuestion={id?:string;prompt:string;type?:"open"|"single_choice"|"scale"|"yes_no";options?:string[];required?:boolean};
export type PatientCareItem={id:string;kind:string;resource_type:string;title:string;instructions:string|null;content:{questions?:Array<string|CareQuestion>;url?:string;prompt?:string;file_path?:string;file_name?:string;file_type?:string};frequency:string;created_at:string};
export default function PatientResourceModal({item,onClose,onSaved}:{item:PatientCareItem;onClose:()=>void;onSaved?:()=>void}){
 const questions=(item.content?.questions||[]).map((question,index):CareQuestion=>typeof question==='string'?{id:String(index),prompt:question,type:'open',required:true}:question);
 const [answers,setAnswers]=useState<string[]>(questions.map(()=>'')),[reflection,setReflection]=useState(''),[message,setMessage]=useState(''),[saving,setSaving]=useState(false);
 useEffect(()=>{(async()=>{const client=createClient(),{data:{user}}=await client.auth.getUser();if(!user)return;const {data}=await client.from('care_item_responses').select('response,status').eq('care_item_id',item.id).eq('patient_id',user.id).eq('response_date',new Date().toISOString().slice(0,10)).maybeSingle();if(data?.response?.answers)setAnswers(data.response.answers);if(data?.response?.reflection)setReflection(data.response.reflection);if(data?.status==='submitted')setMessage('Encuesta diaria completada. Puedes actualizarla si lo necesitas.')})()},[item.id]);
 const answer=(index:number,value:string)=>setAnswers(current=>current.map((item,i)=>i===index?value:item));
 const save=async()=>{if(questions.some((question,index)=>question.required&&!answers[index]?.trim())){setMessage('Responde las preguntas obligatorias antes de guardar.');return}setSaving(true);setMessage('Guardando…');const client=createClient(),{data:{user}}=await client.auth.getUser();if(!user){setSaving(false);setMessage('Tu sesión venció.');return}const response=questions.length?{answers}:{reflection};const {error}=await client.from('care_item_responses').upsert({care_item_id:item.id,patient_id:user.id,response_date:new Date().toISOString().slice(0,10),response,status:'submitted',submitted_at:new Date().toISOString(),updated_at:new Date().toISOString()},{onConflict:'care_item_id,patient_id,response_date'});setSaving(false);setMessage(error?(error.message.includes('care_item_responses')?'Falta activar las respuestas interactivas en Supabase.':error.message):'Encuesta diaria completada. Tu profesional podrá revisarla.');if(!error)onSaved?.()};
 const openFile=async()=>{if(item.content.url){window.open(item.content.url,'_blank','noopener,noreferrer');return}if(!item.content.file_path)return;const {data,error}=await createClient().storage.from('care-resources').createSignedUrl(item.content.file_path,120);if(error||!data?.signedUrl){setMessage('No pudimos abrir el archivo.');return}window.open(data.signedUrl,'_blank','noopener,noreferrer')};
 return <div className="modal-backdrop patient-resource-backdrop" onClick={onClose}><section className="modal patient-resource-modal" onClick={event=>event.stopPropagation()}><button className="modal-close" onClick={onClose}>×</button><p className="eyebrow">ACTIVIDAD COMPARTIDA</p><h2>{item.title}</h2><p className="resource-guidance">{item.instructions||item.content?.prompt||'Responde con calma y a tu ritmo.'}</p>{(item.content.file_path||item.content.url)&&<button className="resource-file-button" onClick={openFile}><span>↓</span><div><strong>{item.content.file_name||'Abrir material'}</strong><small>Material de apoyo</small></div></button>}{questions.map((question,index)=><fieldset className="resource-question" key={question.id||index}><legend>{index+1}. {question.prompt}{question.required?' *':''}</legend>{question.type==='single_choice'?<div className="answer-options">{question.options?.map(option=><label key={option}><input type="radio" name={question.id||String(index)} checked={answers[index]===option} onChange={()=>answer(index,option)}/>{option}</label>)}</div>:question.type==='scale'?<div className="scale-options">{[1,2,3,4,5].map(value=><button type="button" className={answers[index]===String(value)?'selected':''} key={value} onClick={()=>answer(index,String(value))}>{value}</button>)}</div>:question.type==='yes_no'?<div className="answer-options horizontal">{['Sí','No'].map(value=><label key={value}><input type="radio" name={question.id||String(index)} checked={answers[index]===value} onChange={()=>answer(index,value)}/>{value}</label>)}</div>:<textarea value={answers[index]||''} onChange={event=>answer(index,event.target.value)} placeholder="Escribe aquí…"/>}</fieldset>)}{!questions.length&&item.resource_type!=='educational_material'&&<label className="edit-field resource-question"><span>Tu respuesta</span><textarea value={reflection} onChange={event=>setReflection(event.target.value)}/></label>}{message&&<p className="invite-feedback">{message}</p>}{item.resource_type!=='educational_material'&&<button className="primary" disabled={saving} onClick={save}>{saving?'Guardando…':'Guardar respuestas'}</button>}</section></div>
}
