"use client";

import { useEffect, useState } from "react";
import { createClient } from "@/utils/supabase/client";

type ResponseRow={id:string;response_date:string;response:{answers?:string[];reflection?:string};status:string;submitted_at:string|null;care_plan_items:{title:string;resource_type:string;assignment_id:string;content:{questions?:Array<string|{id:string;prompt:string}>}}};

export default function ProfessionalResponses({medical=false}:{medical?:boolean}){
 const [rows,setRows]=useState<ResponseRow[]>([]),[names,setNames]=useState<Record<string,string>>({}),[selected,setSelected]=useState<ResponseRow|null>(null),[loading,setLoading]=useState(true),[message,setMessage]=useState('');
 const load=async()=>{setLoading(true);const client=createClient();const [{data,error},{data:patients}]=await Promise.all([client.from('care_item_responses').select('id,response_date,response,status,submitted_at,care_plan_items(title,resource_type,assignment_id,content)').eq('status','submitted').order('submitted_at',{ascending:false}),client.rpc('my_assigned_patients')]);setRows((data as unknown as ResponseRow[])||[]);setNames(Object.fromEntries(((patients as {assignment_id:string;full_name:string}[])||[]).map(item=>[item.assignment_id,item.full_name])));setMessage(error?(error.message.includes('care_item_responses')?'Falta activar el módulo de respuestas interactivas en Supabase.':error.message):'');setLoading(false)};
 useEffect(()=>{load()},[]);
 const questions=(row:ResponseRow)=>(row.care_plan_items.content?.questions||[]).map(question=>typeof question==='string'?question:question.prompt);
 return <div className="page-content professional-workspace"><div className="page-heading"><p className="eyebrow">{medical?'CONTINUIDAD MÉDICA':'CONTINUIDAD DEL ACOMPAÑAMIENTO'}</p><h1>{medical?'Seguimiento médico':'Seguimiento'}</h1><p>Revisa las actividades que tus pacientes han completado.</p></div><div className="stats follow-up-stats"><section><span>Entregas recibidas</span><strong>{rows.length}</strong><small>Disponibles para revisar</small></section><section><span>Pacientes con actividad</span><strong>{new Set(rows.map(row=>row.care_plan_items.assignment_id)).size}</strong><small>En este registro</small></section><section><span>Estado</span><strong>{rows.length?'Al día':'0'}</strong><small>{rows.length?'Con respuestas':'Sin novedades'}</small></section></div>{message&&<p className="invite-feedback">{message}</p>}{loading?<section className="panel empty-state"><p>Consultando respuestas…</p></section>:rows.length===0?<section className="panel empty-state"><h2>Todo está al día</h2><p>Cuando un paciente complete una encuesta, ejercicio o registro, aparecerá aquí.</p></section>:<section className="panel response-inbox"><div className="section-title"><div><p className="eyebrow">ENTREGAS</p><h2>Respuestas recibidas</h2></div><button onClick={load}>Actualizar</button></div>{rows.map(row=><article key={row.id}><div className="avatar sage">{(names[row.care_plan_items.assignment_id]||'P').split(/\s+/).map(x=>x[0]).join('').slice(0,2)}</div><div><strong>{names[row.care_plan_items.assignment_id]||'Paciente'}</strong><span>{row.care_plan_items.title}</span><small>{new Date(row.submitted_at||row.response_date).toLocaleDateString('es-MX',{day:'numeric',month:'long',year:'numeric'})}</small></div><i>Completada</i><button className="secondary" onClick={()=>setSelected(row)}>Ver respuestas</button></article>)}</section>}{selected&&<div className="modal-backdrop" onClick={()=>setSelected(null)}><section className="modal response-detail-modal" onClick={event=>event.stopPropagation()}><button className="modal-close" onClick={()=>setSelected(null)}>×</button><p className="eyebrow">RESPUESTA DEL PACIENTE</p><h2>{selected.care_plan_items.title}</h2><p>{names[selected.care_plan_items.assignment_id]||'Paciente'} · {new Date(selected.submitted_at||selected.response_date).toLocaleDateString('es-MX')}</p><div className="response-detail-list">{selected.response.answers?.map((answer,index)=><article key={index}><small>{questions(selected)[index]||`Pregunta ${index+1}`}</small><p>{answer||'Sin respuesta'}</p></article>)}{selected.response.reflection&&<article><small>Respuesta</small><p>{selected.response.reflection}</p></article>}</div><button className="primary" onClick={()=>setSelected(null)}>Cerrar</button></section></div>}</div>
}
